channels:
- conda-forge
- nodefaults
dependencies:
# Minimal dependencies in alphabetical order
- dask
- dill
- h5py
- imageio
- ipyparallel
- matplotlib-base
- natsort
- numexpr
- numpy
- pint
- PTable
- python-dateutil
- pyyaml
- requests
- scikit-image
- scikit-learn
- scipy
- sparse
- statsmodels
- sympy
- tifffile >=2019.07.26
- traits
- tqdm

